Controllers/PostAttachmentsController.cs
using kekes.Data;
using kekes.Data.Models;
using kekes.Models;
using kekes.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net.Http.Headers;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace kekes.Controllers
{
    [Authorize]
    public class PostAttachmentsController : Controller
    {
        private static readonly HashSet<String> AllowedExtensions = new HashSet<String> { ".jpg", ".jpeg", ".png", ".gif" };

        private readonly ApplicationDbContext context;
        private readonly UserManager<IdentityUser> userManager;
        private readonly IUserPermissionsService userPermissions;
        private readonly IHostingEnvironment hostingEnvironment;

        public PostAttachmentsController(ApplicationDbContext context, UserManager<IdentityUser> userManager, IUserPermissionsService userPermissions, IHostingEnvironment hostingEnvironment)
        {
            this.context = context;
            this.userManager = userManager;
            this.userPermissions = userPermissions;
            this.hostingEnvironment = hostingEnvironment;
        }

        // GET: PostAttachments/Create
        public async Task<IActionResult> Create(Guid? postId)
        {
            if (postId == null)
            {
                return this.NotFound();
            }

            var post = await this.context.Posts.Include(x => x.User)
                .SingleOrDefaultAsync(m => m.Id == postId);
            if (post == null
                || !this.userPermissions.CanEditPost(post)
                )
            {
                return this.NotFound();
            }

            this.ViewBag.Post = post;
            return this.View(new PostAttachmentEditModel());
        }

        // POST: PostAttachments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid? postId, PostAttachmentEditModel model)
        {
            if (postId == null)
            {
                return this.NotFound();
            }

            var post = await this.context.Posts.Include(x => x.User)
                .SingleOrDefaultAsync(m => m.Id == postId);
            if (post == null
                || !this.userPermissions.CanEditPost(post)
                )
            {
                return this.NotFound();
            }

            var fileName = Path.GetFileName(ContentDispositionHeaderValue.Parse(model.File.ContentDisposition).FileName?.Trim('"'));
            var fileExt = Path.GetExtension(fileName);
            if (!PostAttachmentsController.AllowedExtensions.Contains(fileExt))
            {
                this.ModelState.AddModelError(nameof(model.File), "This file type is prohibited");
            }

            if (this.ModelState.IsValid)
            {
                var postAttachment = new PostAttachment
                {
                    PostId = post.Id,
                    Created = DateTime.UtcNow,
                };

                var attachmentPath = Path.Combine(this.hostingEnvironment.WebRootPath, "attachments", postAttachment.Id.ToString("N") + fileExt);
                postAttachment.Path = $"/attachments/{postAttachment.Id:N}{fileExt}";
                using (var fileStream = new FileStream(attachmentPath, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.Read))
                {
                    await model.File.CopyToAsync(fileStream);
                }

                this.context.Add(postAttachment);
                await this.context.SaveChangesAsync();
                return this.RedirectToAction("Details", "Posts", new { id = post.Id });
            }

            this.ViewBag.Post = post;
            return this.View(model);
        }

        // GET: PostAttachments/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var postAttachment = await this.context.PostAttachments
                .Include(p => p.Post).ThenInclude(x=>x.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (postAttachment == null
                || !this.userPermissions.CanEditPost(postAttachment.Post)
                )
            {
                return this.NotFound();
            }

            return this.View(postAttachment);
        }

        // POST: PostAttachments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var postAttachment = await this.context.PostAttachments
                .Include(p => p.Post).ThenInclude(x => x.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (postAttachment == null
                || !this.userPermissions.CanEditPost(postAttachment.Post)
                )
            {
                return this.NotFound();
            }

            var attachmentPath = Path.Combine(this.hostingEnvironment.WebRootPath, "attachments", postAttachment.Id.ToString("N") + Path.GetExtension(postAttachment.Path));
            System.IO.File.Delete(attachmentPath);
            this.context.PostAttachments.Remove(postAttachment);
            await this.context.SaveChangesAsync();
            return this.RedirectToAction("Details", "Posts", new { id = postAttachment.PostId });
        }
    }
}

Controllers/PostsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using kekes.Data;
using kekes.Data.Models;
using kekes.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using kekes.Services;
using kekes.Hubs;
using Microsoft.AspNetCore.SignalR;

namespace kekes.Controllers
{
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IUserPermissionsService _userPermissions;
        private readonly ITagsService _tags;

        public PostsController(ApplicationDbContext context, UserManager<IdentityUser> userManager, IUserPermissionsService userPermissions, ITagsService tags)
        {
            _context = context;
            _userManager = userManager;
            _userPermissions = userPermissions;
            _tags = tags;
        }

        // GET: Posts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Posts.Include(p => p.Section);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Section).Include(p => p.Tags).Include(p => p.User).Include(x => x.Attachments).Include(p => p.Comments).ThenInclude(x => x.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Posts/Create
        [Authorize]
        public IActionResult Create(Guid sectionId)
        {
            if (sectionId != Guid.Empty)
            {
                var model = new PostCreateViewModel() { SectionId = sectionId };
                return View(model);
            }
            return NotFound();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PostCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var section = await _context.Sections
                .FirstOrDefaultAsync(m => m.Id == model.SectionId);
                if (section == null)
                {
                    return NotFound();
                }
                var post = new Post
                {
                    Id = Guid.NewGuid(),
                    SectionId = model.SectionId,
                    Name = model.Name,
                    Text = model.Text,
                    Created = DateTime.Now,
                    LastActivity = DateTime.Now,
                    User = await _userManager.GetUserAsync(HttpContext.User)
                };
                _context.Add(post);
                await _context.SaveChangesAsync();

                return RedirectToAction("Details", "Sections", new { id = model.SectionId });
            }
            return View(model);
        }

        // GET: Posts/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.Include(x => x.User).FirstOrDefaultAsync(x => x.Id == id);
            if (post == null)
            {
                return NotFound();
            }
            if (!this._userPermissions.CanEditPost(post))
            {
                return this.Unauthorized();
            }

            var model = new PostEditViewModel
            {
                Id = post.Id,
                Name = post.Name,
                Text = post.Text
            };

            return View(model);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PostEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var post = await _context.Posts.Include(x => x.User).FirstOrDefaultAsync(x => x.Id == model.Id);
                if (post == null)
                {
                    return NotFound();
                }
                if (!this._userPermissions.CanEditPost(post))
                {
                    return this.Unauthorized();
                }

                post.Name = model.Name;
                post.Text = model.Text;

                await _context.SaveChangesAsync();

                return RedirectToAction("Details", "Posts", new { id = model.Id });
            }
            return View(model);
        }

        // GET: Posts/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Section).Include(p => p.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }
            if (!this._userPermissions.CanEditPost(post))
            {
                return this.Unauthorized();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var post = await _context.Posts.Include(x => x.User).FirstOrDefaultAsync(x => x.Id == id);
            if (!this._userPermissions.CanEditPost(post))
            {
                return this.Unauthorized();
            }

            _context.Posts.Remove(post);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Sections", new { id = post.SectionId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddComment(CommentCreateViewModel model)
        {
            if (!this.HttpContext.User.Identity.IsAuthenticated)
            {
                return this.Unauthorized();
            }

            var post = await _context.Posts
            .FirstOrDefaultAsync(m => m.Id == model.PostId);
            if (post == null)
            {
                return NotFound();
            }

            var comment = new Comment
            {
                Id = Guid.NewGuid(),
                Text = model.Text,
                Created = DateTime.Now,
                PostId = model.PostId,
                User = await _userManager.GetUserAsync(HttpContext.User)

            };
            post.LastActivity = DateTime.Now;
            _context.Add(comment);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Posts", new { id = model.PostId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddTag(TagAddViewModel model)
        {
            var post = await _context.Posts.Include(x => x.User)
            .FirstOrDefaultAsync(m => m.Id == model.PostId);
            if (post == null)
            {
                return NotFound();
            }

            if (!_userPermissions.CanEditPost(post))
            {
                return this.Unauthorized();
            }

            await _tags.AddTagToPostAsync(model.Text, post.Id);

            return RedirectToAction("Details", "Posts", new { id = model.PostId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SubscribeOnTag(Guid tagId, Guid postId)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);

            await _tags.SubscribeUserOnTagAsync(tagId, user);

            return RedirectToAction("Details", "Posts", new { id = postId });
        }

        [Authorize(Roles = ApplicationRoles.Administrators)]
        [HttpPost, ActionName("DeleteComment")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteComment(Guid id)
        {
            var comment = await _context.Comments.Include(x => x.User).FirstOrDefaultAsync(x => x.Id == id);

            _context.Comments.Remove(comment);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Posts", new { id = comment.PostId });
        }

        private bool PostExists(Guid id)
        {
            return _context.Posts.Any(e => e.Id == id);
        }
    }
}

Views/Posts/Create.cshtml
@model PostCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<div class="mainContainer col-9 p-2 border rounded ps-3 pe-3 pb-2">
    <div class="createNewPostsArea row d-flex justify-content-center">
    <h2 class="text-center mt-3">Создать новый пост</h2>
    <div class="col-md-7">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"><h6>Название</h6></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" for="FormControlTextarea" class="mt-2 mb-2 form-label"><h6 class="m-0">Описание</h6></label>
                <textarea  asp-for="Text" class="form-control" id="FormControlTextarea" rows="3"></textarea>
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <input asp-for="SectionId" value="@Model.SectionId" class="form-control" type="hidden" />
            <br />
            <div class="form-group text-center w-100">
                <input type="submit" value="Создать" class="btnCreateNewPost btn btn-dark mt-3 w-100" />
            </div>
        </form>
    </div>

    <a asp-action="Index" class="text-secondary text-end mt-4">Вернуться к списку постов</a>
</div>




</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Posts/Delete.cshtml
@model kekes.Data.Models.Post

@{
    ViewData["Title"] = "Delete";
}


<div class="mainContainer col-9 p-2 border rounded ps-3 pe-3 pb-4">
    <h3>Вы действительно хотите удалить этот пост?</h3>
    <div>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                Название
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class = "col-sm-2">
                Описание
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Text)
            </dd>
            <dt class = "col-sm-2">
                Дата создания
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Created)
            </dd>
            <dt class = "col-sm-2">
                Дата последней активности
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.LastActivity)
            </dd>
        </dl>
        
        <form asp-action="Delete" class="d-flex justify-content-between">
            <div>
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Удалить" class="btnDeleteAttachment btn btn-danger" /> 
            </div>
            <div class="align-self-end">
                <a asp-action="Details" asp-route-id="@Model.Id" class='text-secondary'>Вернуться к разделам</a>
            </div>     
        </form>
    </div>
</div>

Views/Posts/Details.cshtml
@using kekes.Services
@using Microsoft.AspNetCore.Identity
@model kekes.Data.Models.Post
@inject IUserPermissionsService UserPermissions
@inject SignInManager<IdentityUser> SignInManager
@{
    ViewData["Title"] = "Details";
    var canEditPost = UserPermissions.CanEditPost(this.Model);
}


<div class="mainContainer col-9 p-2 border rounded ps-3 pe-3 pb-4">
    <div class="blog-post-details">
        <h1>@Model.Name</h1>
        <div class="blog-post-info d-flex flex-row justify-content-between">
            <div>@Model.User.UserName | @Model.Section.Name | @Model.Created</div>
            <div>
                @if (canEditPost)
                {
                    <a asp-action="Edit" asp-route-id="@Model.Id" class="text-secondary">Редактировать</a>
                    <text>|</text> <a asp-action="Delete" asp-route-id="@Model.Id" class="text-secondary">Удалить</a>
                }
            </div>
        </div>

        <h3 class="mb-2 mt-2">Описание</h3>
        <div class="blog-post-text ms-3">@Model.Text</div>
    </div>

    <div class="d-flex justify-content-between">
        <h3 class="mb-4 mt-2">Вложения</h3>
        @if (canEditPost)
        {
            <p class="text-end align-self-end">
                <a asp-action="Create" asp-controller="PostAttachments" asp-route-postId="@Model.Id" class="btnAddComment btn btn-dark">Добавить</a>
            </p>
        }
    </div>


    @if (Model.Attachments != null)
    {
        <div class="row">
            @foreach (var item in Model.Attachments?.OrderByDescending(x => x.Created))
            {
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <img src="@item.Path" alt="Image" class="img-fluid  rounded" />
                        @if (canEditPost)
                        {
                            <div class=" caption text-center">
                                <p><a asp-action="Delete" asp-controller="PostAttachments" asp-route-id="@item.Id" class="btnDeleteAttachment btn btn-danger mt-2">Удалить</a></p>
                            </div>
                        }
                    </div>
                </div>
            }
        </div>
    }

    <div id="placeTags" class="d-flex justify-content-between">
        <h3 class="mb-3 mt-2">Теги</h3>
        @if (canEditPost)
        {
            <p class="text-end align-self-end">
                <a id="btnAddTags" class="btnAddComment btn btn-dark">Добавить</a>
            </p>
        }
    </div>

    <div class="d-flex flex-row ms-3 mb-2">
        @foreach (var item in Model.Tags)
        {

            <h6 id="tag-@item.Text" data-bs-toggle="modal" data-bs-target="#exampleModal-@item.Text" class="tags me-3">#@item.Text</h6>

            <div class="modal fade" id="exampleModal-@item.Text" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header p-0 m-0">
                            <button type="button" class="btn-close end-0 me-2 mt-1 mb-1" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                        </div>
                        <div class="modal-body d-flex justify-content-center">
                            <form method="post" asp-action="SubscribeOnTag" asp-controller="Posts" asp-route-tagId="@item.Id" asp-route-postId="@Model.Id">
                                <button type="submit" class="btnSubmit btn btn-dark me-1">Подписаться на тег @item.Text</button>
                                <button type="button" class="btnSubmit btn btn-dark ms-1">Посты с тегом @item.Text</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

    @if (canEditPost)
    {
        <form method="post" asp-action="AddTag" asp-controller="Posts" id="createTag" class="d-none">
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Название тега</label>
                <input name="Text" class="form-control" />
                <input name="PostId" value="@Model.Id" class="form-control" type="hidden" />
            </div>
            <button id="btnCreateTag" type="submit" class="btnSubmit btn btn-dark align-self-end mb-3">Создать</button>
        </form>
    }


    <h3 class="mb-4">Обсуждение</h3>

    @if (SignInManager.IsSignedIn(User))
    {
        <form method="post" asp-action="AddComment">
            <input name="Text" class="form-control inputFields" />
            <input name="PostId" value="@Model.Id" class="form-control border-2 border-dark" type="hidden" />
            <div class="form-group mt-3 w-100 text-end">
                <input type="submit" value="Комментировать" class="btnAddComment btn btn-dark end-0" />
            </div>
        </form>
    }
    else
    {
        <text>
            Для возможности комментирования необходимо
            <a asp-area="Identity" asp-page="/Account/Login" asp-route-returnUrl="@Url.Action("Details", "Posts", new { id = @Model.Id })">войти</a>
        </text>
    }

    <div class="blog-posts">
        <div class="blog-posts-items">
            @foreach (var item in Model.Comments.OrderByDescending(x => x.Created))
            {
                <div class="blog-post panel panel-default rounded bg-light border border-2 border-dark mt-3 ">
                    <div class="panel-heading inputFields border-bottom border-1 border-dark  ps-2 pt-1 pb-1 w-100 d-flex flex-row justify-content-between">
                        <div class="text-dark ps-2">@item.User.UserName | @item.Created</div>
                        <div class="text-end text-dark pe-3">
                            @if (UserPermissions.CanEditPostComment(item))
                            {
                                <form method="post" asp-action="DeleteComment" asp-controller="Posts" asp-route-id="@item.Id">
                                    <div class="form-actions no-color">
                                        <input type="submit" value="Удалить" />
                                    </div>
                                </form>
                            }
                        </div>
                    </div>
                    <div class="panel-body inputFields pt-2 pb-2 ps-4 ">
                        <div class="blog-post-text inputFields text-dark">@item.Text</div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<div class="col-1"></div>
<div class="mainContainer col-2 p-2 border rounded d-flex align-self-start flex-md-column">
    <h6 class="text-light text-center w-100">Объявления</h6>
    <div id="newAnnouncements">
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
    function a(){
        var counter = 0;
        $.ajax({
            type: 'GET',
            url: '/Announcements/GetAnnouncements',
            success: function (response) {
                $.each(response, function (index, value) {
                    counter++;
                    if(counter <= 3)
                    {
                        $('#newAnnouncements').append('<p id=list'+value.id+'>' + value.title + ' - ' + value.date + '</p>');
                    }

                })
            },
            error: function (error) {
                console.error(error);
            }
        })
    }

    a()

       document.getElementById('btnAddTags').onclick = function () {
        document.getElementById('createTag').className = "";
    }

    document.getElementById('btnCreateTag').onclick = function () {
        document.getElementById('createTag').className = "d-none";
    }



</script>

Views/Posts/Edit.cshtml
@using kekes.Models
@model PostEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="mainContainer col-9 p-2 border rounded ps-3 pe-3 pb-4">
<h1>Редактирование поста</h1>

<hr />
<div class="row">
    <div class="col-md-12 w-100">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="@Model.Id" />
            <div class="form-group w-50">
                <label asp-for="@Model.Name" class="control-label">Название</label>
                <input asp-for="@Model.Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group  w-50">
                <label asp-for="@Model.Text" class="control-label">Описание</label>
                <input asp-for="@Model.Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group d-flex justify-content-between w-100 mt-3">
                <input type="submit" value="Сохранить" class="btnSubmit btn btn-dark" />
                <a asp-action="Details" asp-route-id="@Model.Id" class="text-secondary end-100 text-end mt-4">Вернуться к посту</a>
            </div>
        </form>
    </div>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Posts/Index.cshtml
@model IEnumerable<kekes.Data.Models.Post>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Text)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Created)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastActivity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Section)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
           <tr>
               <td>
                   @Html.DisplayFor(modelItem => item.Name)
               </td>
               <td>
                   @Html.DisplayFor(modelItem => item.Text)
               </td>
               <td>
                   @Html.DisplayFor(modelItem => item.Created)
               </td>
               <td>
                   @Html.DisplayFor(modelItem => item.LastActivity)
               </td>
               <td>
                   @Html.DisplayFor(modelItem => item.Section.Id)
               </td>
               <td>
                   <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                   <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                   <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
               </td>
           </tr>
        }
    </tbody>
</table>